---
title: "R programming Part 1 "
output: html_notebook
---

#Project 1: Weighted Dice
The very Basics
```{r}
1 + 1
2*3
4 - 1
6 / (4 - 1)
100:130
```

Exercise 2.1 (Magic with Numbers)
1. Choose any number and add 2 to it.
2. Multiply the result by 3.
3. Subtract 6 from the answer.
4. Divide what you get by 3.
```{r}
3 + 2
5 * 3
15 - 6
9 / 3
```

2.2 Objects
```{r}
a <- 1 
a
a + 2

die <- 1:6
die

#object names you have already used 
ls()
```

```{r}
die - 1
die/2
die * die

1:2
1:4
die
die + 1:2
die + 1:4
```

```{r}
#inner multiplication
die %*% die

#outer multiplication 
die %o% die

#transpose with t, take its determinant with det
```

2.3 Functions
```{r}
round(3.1415)
factorial(3)

mean(1:6)
mean(die)
round(mean(die))
```

```{r}
sample(x = 1:4, size = 2)

sample(x = die, size = 1)
sample(x = die, size = 1)
sample(x = die, size = 1)
sample(die, size = 1)

#lookup functions arguments with args
args(round)
round(3.1415, digits = 2)
```

2.3.1 Sample with replacement
```{r}
#correct way to simulate a pair of dice
dice <- sample(die, size = 2, replace = TRUE)
dice
sum(dice)
```

2.4 Writing Your Own Functions
```{r}
my_function <- function() {}

roll <- function() {
  die <- 1:6
  dice <- sample(die, size = 2, replace = TRUE)
  sum(dice)
}

roll
roll()
```

2.5 Arguments
```{r}
roll2 <- function(bones) {
  dice <- sample(bones, size = 2, replace = TRUE)
  sum(dice)
}
roll2(bones = die)
roll2(bones = 1:20)
```

```{r}
roll3 <- function(bones = 1:6) {
  dice <- sample(bones, size = 2, replace = TRUE)
  sum(dice)
}
roll3()
```

3.1 packages, plots
ˆ
```{r}
library(ggplot2)
```
```{r}
x <- c(-1, -0.8, -0.6, -0.4, -0.2, 0, 0.2, 0.4, 0.6, 0.8, 1)
y <- x^3
x ; y

#qplot makes a scatterplot when given 2 vectors
qplot(x,y)

```

```{r}
#qplot makes a histogram when given 1 vector
x <- c(1, 2, 2, 2, 3, 3)
qplot(x, binwidth = 1)

x2 <- c(1, 1, 1, 1, 1, 2, 2, 2, 2, 3, 3, 4)
qplot(x2, binwidth = 1)

x3 <- c(0, 1, 1, 2, 2, 2, 3, 3, 4)
qplot(x3, binwidth = 1)
```

```{r}
replicate(3, 1+1)

replicate(10, roll())

rolls <- replicate(10000, roll())
qplot(rolls, binwidth = 1)
```

3.2 weighted die
```{r}
#old func
roll <- function() {
  die <- 1:6
  dice <- sample(die, size = 2, replace = TRUE)
  sum(dice)
}

#new scam function
roll <- function() {
  die <- 1:6
  dice <- sample(die, size = 2, replace = TRUE, 
    prob = c(1/8, 1/8, 1/8, 1/8, 1/8, 3/8))
  sum(dice)
}

```

```{r}
#new plot with weithed results
rolls <- replicate(10000, roll())
qplot(rolls, binwidth = 1)
```


