---
title: "Visualizations"
output: html_notebook
---

#####################PLOTS#################################

```{r}

####GENERAL PLOTS####

#Looking for amount of years competed 
Years_comp_graph <- 
  Merged_500 %>% group_by(Team) %>% count(Team) %>%
  arrange(desc(n)) %>% ggplot(aes(x = n)) + 
  geom_histogram(bins = 11,color="darkgreen", fill="lightgreen") +
  labs(title="Teams Competing History",
       subtitle = "How consistently are teams competing?",
       x="Years competing", 
       y = "Amount of Teams") +
  theme_fivethirtyeight() + 
  theme(axis.title = element_text(), text = element_text(family = "Verdana")) 
#save
ggsave("years_competing.png")


#Total Number of teams competed each year
Num_teams_compete_graph <- 
  Merged_500 %>% group_by(Year) %>% ggplot(aes(x = Year)) +
  geom_histogram(bins = 11, color="darkblue", fill="lightblue") +
  labs(title="Number of Teams Competing by Year",
       subtitle = "How many teams were competing/recorded each year?",
       x="Year", 
       y = "Amount of Teams") +
  theme_fivethirtyeight() + 
  theme(axis.title = element_text(), text = element_text(family = "Verdana"))
#save
ggsave("teams_competing_by_year.png")

#Number of Teams in each division
Num_teams_division_graph <- 
  Merged_500 %>% group_by(Division) %>% ggplot(aes(x = Year, fill = Division)) +
  geom_bar(position = "dodge") +
  labs(title="Number of Teams Competing by division",
       subtitle = "How many teams compete in each division?",
       x="Year",
       y = "Amount of Teams")+
  theme_fivethirtyeight() + 
  theme(axis.title = element_text(), text = element_text(family = "Verdana"))
#save
ggsave("Num_teams_by_division.png")

#Race time by division by year
Time_year_division_graph <-Merged_500 %>% group_by(Division)%>% 
  #filter(Year >=2012) %>% 
  ggplot(aes(x = factor(Year), y = Overall_Seconds, colour = Division)) +
  geom_boxplot() + 
  labs(title = "Race Times by Division over Time",
       subtitle = "How do race times differ between divisions?",
       x = "Year",
       y = "Race Time") +
  theme_fivethirtyeight() + 
  theme(axis.title = element_text(), text = element_text(family = "Verdana"))
#save
ggsave("race_time_by_division.png")
  

#Mean vs Median by Year
Total_Median_Mean_graph <- 
  sum_stats_All %>% ggplot(aes(x=Year, y=m)) + 
  geom_line(colour = "red", size  = 1.1, alpha = 0.8) +
  geom_line(aes(x=Year, y=med), colour = "blue", size = 1.1) + 
  labs(title="Mean vs Median Overall Time",
       subtitle = "How do the mean and median race times differ overtime?",
       x="Year", 
       y = "Overall Time") +
  theme_fivethirtyeight() + 
  theme(axis.title = element_text(), text = element_text(family = "Verdana"))
#save
ggsave("mean_vs_median_race_times.png")

#Mean by Tier by year
Diff_between_tiers <- Tiers_year_means %>% 
  ggplot(aes(x=Group.2,y=Overall_Seconds, group=Group.1, 
             colour = as.factor(Group.1))) + 
  geom_line() + geom_point() + 
  labs(title="Difference in Tiers over Years",
       subtitle = "How do the mean race times differ between tiers over time?",
       x="Year", 
       y = "Overall Time") + 
  theme_fivethirtyeight() + 
  theme(axis.title = element_text(), text = element_text(family = "Verdana"))
#save
ggsave("race_time_by_teir.png")

#display graphs

Years_comp_graph
Num_teams_compete_graph
Num_teams_division_graph
Time_year_division_graph
Total_Median_Mean_graph
Diff_between_tiers

```


```{r}

####MIXED DIVISION PLOTS####

#Comparing top 5 Ranked ranked teams 
Top_5_Mixed_Graph <- 
  merged_mixed_500 %>% filter(Rank <= 5 ) %>% 
  ggplot(aes(x=Year,y=Overall_Seconds, group=Rank, 
             colour = as.factor(Rank))) + 
  geom_line() + geom_point() 

#RENAME LABELS
Bot_5 <- merged_mixed_500 %>% group_by(Year) %>% top_n(5,Rank) 

labels = c("Fifth Last", "Fourth Last", "Third Last", "Second Last", " Last")
last_labels = rep(labels, length(Rank_500s_mixed_list))
Bot_5$labels = last_labels

#Compare bottom 5 throughout the years
Bot_5_Mixed_Graph <- 
  Bot_5 %>% group_by(labels) %>%  
  ggplot(aes(x = Year, y = Overall_Seconds, colour = labels)) +
  geom_point() + geom_line()

Top_5_Mixed_Graph
Bot_5_Mixed_Graph
```
