---
title: "Dragon Boat Rankings"
output: html_notebook
---

########################LIBRARIES########################## 

```{r}

#Libraries 
library(XML)
library(tidyverse)
library(rvest)
library(data.table)
library(lubridate)
library(dplyr)
library(ggthemes)
library(extrafont)
library(gganimate)
```

###################SUMMARY STATS######################

```{r}
###########Summary Statistics##############
#Mixed
sum_stats_Mixed <- 
  merged_mixed_500 %>% group_by(Year) %>%
  summarize(m=mean(Overall_Seconds),s=sd(Overall_Seconds), n=n(),
            med=median(Overall_Seconds),
            Q1=quantile(Overall_Seconds, 0.25), 
            Q3=quantile(Overall_Seconds, 0.75)) 

#Women
sum_stats_Women <- 
  merged_Women_500 %>% group_by(Year) %>%
  summarize(m=mean(Overall_Seconds),s=sd(Overall_Seconds), n=n(),
            med=median(Overall_Seconds),
            Q1=quantile(Overall_Seconds, 0.25), 
            Q3=quantile(Overall_Seconds, 0.75)) 

#Open
sum_stats_Open <- 
  merged_Open_500 %>% group_by(Year) %>%
  summarize(m=mean(Overall_Seconds),s=sd(Overall_Seconds), n=n(),
            med=median(Overall_Seconds),
            Q1=quantile(Overall_Seconds, 0.25), 
            Q3=quantile(Overall_Seconds, 0.75)) 

#ALL
sum_stats_All <- 
  Merged_500 %>% group_by(Year) %>%
  summarize(m=mean(Overall_Seconds),s=sd(Overall_Seconds), n=n(),
            med=median(Overall_Seconds),
            Q1=quantile(Overall_Seconds, 0.25), 
            Q3=quantile(Overall_Seconds, 0.75)) 

#mixed tiers
Tiers_year_means <- 
  aggregate(with_tiers_mixed, 
          by = list(with_tiers_mixed$Tier,with_tiers_mixed$Year), mean) %>%
  select(Group.1, Group.2, Overall_Seconds)


sum_stats_Mixed
sum_stats_Women
sum_stats_Open
sum_stats_All

means <- data.frame(sum_stats_Mixed$m,sum_stats_Women$m,sum_stats_Open$m)
```


######################STATISTICAL INFERENCE###################

```{r}

# %90 Confidence interval on overall time
t.test(merged_mixed_500$Overall_Seconds, conf.level = 0.90)

```


