---
title: "Data Wrangling"
output: html_notebook
---
########################LIBRARIES########################## 

```{r}

#Libraries 
library(XML)
library(tidyverse)
library(rvest)
library(data.table)
library(lubridate)
library(dplyr)
```

##MAke functions for more efficiency 
########################DATA WRANGLING######################
```{r}
################GET URLS FROM MOFOS########################
#URL 500 mixed rankings 
Files_mixed_500s <- paste0("http://www.mofosdragonboat.com/Rankings/", 2009:2019, "RankingsMixed500.html")

#URL 500 Women rankings 
Files_Women_500s <- paste0("http://www.mofosdragonboat.com/Rankings/", 2009:2019, "RankingsWomens500.html")

#URL 500 Open rankings 
Files_Open_500s <- paste0("http://www.mofosdragonboat.com/Rankings/", 2009:2019, "RankingsOpen500.html")


################Make html tables to dataframes###############
#Function for html to list of dfs 
Html_to_dfs <- function(url_name){
  return(sapply(url_name, function(x) try(as_tibble(readHTMLTable(x, skip.rows = 1)))))
}
#Mixed 500s
Rank_500s_mixed_list <- Html_to_dfs(Files_mixed_500s)

#Womens 500s
Rank_500s_Women_list <- Html_to_dfs(Files_Women_500s)

#Open 500s
Rank_500s_Open_list <- Html_to_dfs(Files_Open_500s)

#####get first 3 columns of dfs and add years, Division, Number of regattas attended####
#Function for getting required columns and adding columns
x = 1
year = 2009
while (x <= length(Rank_500s_mixed_list)) {
  #Add Number of Regattas attended
  Rank_500s_mixed_list[[x]]$Regattas_Attended <- (rowSums((Rank_500s_mixed_list[[x]]) != "Â")) - 3 
  Rank_500s_Women_list[[x]]$Regattas_Attended <- (rowSums((Rank_500s_Women_list[[x]]) != "Â")) - 3
  Rank_500s_Open_list[[x]]$Regattas_Attended <- (rowSums((Rank_500s_Open_list[[x]]) != "Â")) -3 
  
  #Get Team, Overall, Rank, Number of Regattas
  Rank_500s_mixed_list[[x]] <- Rank_500s_mixed_list[[x]] %>% select(Rank, Team, Overall, Regattas_Attended)
  Rank_500s_Women_list[[x]] <- Rank_500s_Women_list[[x]] %>% select(Rank, Team, Overall, Regattas_Attended)
  Rank_500s_Open_list[[x]] <- Rank_500s_Open_list[[x]] %>% select(Rank, Team, Overall, Regattas_Attended)
  
  #Add Year column
  Rank_500s_mixed_list[[x]]$Year <- rep(year, nrow(Rank_500s_mixed_list[[x]]))
  Rank_500s_Women_list[[x]]$Year <- rep(year, nrow(Rank_500s_Women_list[[x]]))
  Rank_500s_Open_list[[x]]$Year <- rep(year, nrow(Rank_500s_Open_list[[x]]))
  
  #Add Division Column
  Rank_500s_mixed_list[[x]]$Division <- rep("Mixed", nrow(Rank_500s_mixed_list[[x]]))
  Rank_500s_Women_list[[x]]$Division <- rep("Womens", nrow(Rank_500s_Women_list[[x]]))
  Rank_500s_Open_list[[x]]$Division <- rep("Open", nrow(Rank_500s_Open_list[[x]]))
  
 
  #Count update
  x = x + 1 
  year = year + 1
} 

#merge data so one df contains all information from their list
merged_mixed_500 = Rank_500s_mixed_list[[1]]
merged_Women_500 = Rank_500s_Women_list[[1]]
merged_Open_500 = Rank_500s_Open_list[[1]]

a = 2
while (a <= length(Rank_500s_mixed_list)) {
  #Merge dfs from lists
  merged_mixed_500 = rbind(merged_mixed_500, Rank_500s_mixed_list[[a]])
  merged_Women_500 = rbind(merged_Women_500, Rank_500s_Women_list[[a]])
  merged_Open_500 = rbind(merged_Open_500, Rank_500s_Open_list[[a]])
  a = a + 1 
} 

#add overall seconds and change rank to numeric
#Mixed
merged_mixed_500$Overall_Seconds <-
  period_to_seconds(ms(merged_mixed_500$Overall))
merged_mixed_500$Rank <- as.numeric(merged_mixed_500$Rank)
#Women
merged_Women_500$Overall_Seconds <-
  period_to_seconds(ms(merged_Women_500$Overall))
merged_Women_500$Rank <- as.numeric(merged_Women_500$Rank)
#Open
merged_Open_500$Overall_Seconds <-
  period_to_seconds(ms(merged_Open_500$Overall))
merged_Open_500$Rank <- as.numeric(merged_Open_500$Rank)

#Add Tiers Teams fall into for mixed teams
#Mixed
with_tiers_mixed <- merged_mixed_500
with_tiers_mixed$Tier <-
  ifelse(with_tiers_mixed$Overall_Seconds < 125, "A", 
          ifelse(with_tiers_mixed$Overall_Seconds >= 125 &
                   with_tiers_mixed$Overall_Seconds < 130, "B", 
                 ifelse(with_tiers_mixed$Overall_Seconds >= 130 &
                          with_tiers_mixed$Overall_Seconds < 135, "C",
                        ifelse(with_tiers_mixed$Overall_Seconds >= 135 &
                                 with_tiers_mixed$Overall_Seconds < 140, "D",
                               ifelse(with_tiers_mixed$Overall_Seconds >= 140 &
                                        with_tiers_mixed$Overall_Seconds < 145, "E",
                                      ifelse(with_tiers_mixed$Overall_Seconds >= 145, "F", "yeet"
                                 )
         )))))

  
#####MERGE ALL INFO INTO ONE DF#####
#Put all that together
Merged_500 <- 
  do.call("rbind", list(merged_mixed_500,merged_Women_500,merged_Open_500))

#GEt University Teams
Universities <- c("GBC HUSKIES", "WATERLOO WARRIORS GOLD", "UOFT PHARMACY PAINKILLERS", "YORK LIONS - BLACK", "IRON DRAGONS PURPLE", "	UNIVERSITY OF TORONTO PACEMAKERS", "PLAK ATTACK", "UNIVERSITY COLLEGE-HYDRAS", "RYERSON RAMS", "LAURIER DRAGON HAWKS", "U OF T PHYSICAL THERAPY MOTOR UNIT", "CRIMSON DRAGONS", "YORK LIONS - RED", "CRIMSON TIDE", "UNIVERSITY COLLEGE-WATER DRAGONS", "IRON DRAGONS GOLD", "STALLIONS - WESTERN", "HOLY MAC-A-ROW-NI", "MUSTANGS- WESTERN", "IRON DRAGONS BLUE", "WATERLOO WARRIORS BLACK", "NEW DRAGONS", "ROTMAN COMMERCE LIQUID ASSETS", "HOLY MAC-ROW")
Uni_500 <- merged_mixed_500 %>% filter(Team %in% Universities)
Uni_500

save(merged_mixed_500, file = "Mixed_500.Rda")
save(merged_Open_500, file = "Open_500.Rda")
save(merged_Women_500, file = "Women_500.Rda")
save(Merged_500, file = "Merged_500.Rda")
save(with_tiers_mixed, file = "Mixed_500_with_tiers")
save(Uni_500, file = "University_500.Rda")
```
